### PR TITLE
fix missing zero in one day cache number

### PR DESCRIPTION
**Pull request by albertstill**
86400000 milliseconds is 1 day

https://www.google.com.au/search?q=86400000+milliseconds+to+days&spell=1&sa=X&ved=0ahUKEwiTmITf1Z7VAhXMpJQKHUojDWwQvwUIIygA&biw=1440&bih=776

### CODE REVIEW

**Comment by leo** [comment]
Thank you! But the MDN documentation states that it should be [seconds](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control).

**Comment by albertstill** [comment]
I know the Cache-Control HTTP header is in seconds, but this is a `send` options object, which is in [milliseconds](https://github.com/pillarjs/send#maxage). Right now it's missing a single zero, so it equates to 2.4 hours, and your API is saying it should be [24 hours](https://github.com/zeit/serve/blob/dae446eb35480cb1db3fedd7e37983378093945c/lib/options.js#L16).

**Comment by leo** [comment]
Oh,

**Comment by leo** [comment]
[Released!](https://github.com/zeit/serve/releases/tag/6.0.3)

**Comment by albertstill** [comment]
cool thanks

**Pull request merged**
