### PR TITLE
Add default port: 3000

### LINKED ISSUE #75: Include Default Port
Upgrading from `2.0` to `2.4` breaks my simple use case unless I specify a port.

```json
{
  "start-2.0": "serve dist -s",
  "start-2.4": "serve dist -s -p 3000"
}
```

It also breaks whether or not the `-s` flag is present.

### PR DESCRIPTION
**Pull request by lukeed**
Closes #75

### CODE REVIEW

**Comment by leo** [comment]
I removed this because I wanted the default port to be a random one.

**Comment by lukeed** [comment]
Oh, okay. I was thrown off because it doesn't work at all without explicitly setting the flag or env var.

**Comment by leo** [comment]
@lukeed What's the node version you're on it? Because if you don't pass a port to a HTTP server in node, it will normally just use a random open port.

**Comment by lukeed** [comment]
I'm on `6.9.1` 🤔

**Comment by leo** [comment]
@lukeed What's the error you're getting?

**Comment by lukeed** [comment]
This happened to me on a `now` deployment as well, even when `serve` was the only dependency installed. So I don't think I'm alone here?

```
RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1388:5)
    at Object.<anonymous> (/Users/lukee/repos/personal/apps/colors-app/node_modules/serve/lib/index.js:47:8)
    at Module._compile (module.js:570:32)
    at Module._compile (/Users/lukee/repos/personal/apps/colors-app/node_modules/async-to-gen/register.js:37:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/lukee/repos/personal/apps/colors-app/node_modules/async-to-gen/register.js:40:5)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by leo** [comment]
@lukeed Fixed! Please get the latest update.

**Comment by lukeed** [comment]
Cool, thanks!

**Pull request closed without merging**
