### PR TITLE
Open in browser option

### PR DESCRIPTION
**Pull request by kennedyrose**

### CODE REVIEW

**Comment by sant123** [comment]
@kennedyrose, ¿may you resolve the conflicts? Meanwhile @leo answers.

**Comment by Telokis** [comment]
Anything new with this?

**Comment by JounQin** [comment]
When will the conflicts be resolved and this PR to be merged????

**Comment by rauchg** [comment]
I'm -1 on this. Let's keep `serve` simple.

**Comment by FDiskas** [comment]
`The package has been renamed to `open`

**Pull request closed without merging**
