### PR TITLE
feat: serve specified directory

### PR DESCRIPTION
**Pull request by KnisterPeter**
Serves specified directory, defaults to cwd

### CODE REVIEW

**Comment by matheuss** [comment]
You already can do that by running `serve path/to/directory` 🤔

**Comment by KnisterPeter** [comment]
I've tried that and it failed in combination with `--single`.

**Comment by KnisterPeter** [comment]
Maybe I misunderstood single, but I thought it might be there for serving a single index.html and some static resources (like images or js or css)

**Comment by jamo** [comment]
Shouldn't we rather fix the current method for specifying folder to work with `--single` - than add a new option for something that existed 🤔

**Comment by jamo** [comment]
Seems like this https://github.com/zeit/serve/blob/master/lib/index.js#L23 is just too naive - afaik the path to directory should be last argument...

**Comment by KnisterPeter** [comment]
So lets abandon this.

**Pull request closed without merging**
